### ISSUE TITLE
Redirection failed for securitySchemes oauth2

### ISSUE THREAD

**Issue by malys** [mykeels/openapi-browser#2]
Hi mykeels,
Thank you for openapi-browser.
I'm trying to use your project and I have an issue corresponding to:
https://github.com/moon0326/swagger-ui-watcher/issues/31

Using Oauth2 security scheme with authorization code flow,  Swagger UI asks to redirect by default to '/oauth2-redirect.html' but in your case this resource is not exposed .
Do you think that it could be possible to add in editor.ts something like that:

```
  app.get('/oauth2-redirect.html', (req, res) => {
    res.sendFile(config.editorPath+ "/oauth2-redirect.html");
  });
```
Thanks

**Comment by mykeels** [comment]
I think so. Can you make the PR?

**Comment by malys** [comment]
https://github.com/mykeels/openapi-browser/pull/3 done
